FROM python:3.9-slim

# postgresql 및 컴파일을 위한 시스템 패키지 설치
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

RUN pip install mlflow psycopg2-binary boto3 cryptography